### ISSUE TITLE
dockerのLSPとcoc.nvimを接続する

### ISSUE THREAD

**Issue by dondakeshimo** [dondakeshimo/dotfiles#39]
<https://koyamay.hatenablog.com/entry/2020/01/05/124346>

こういうイメージ

そのほか検討事項
- 全てインストール済みの環境が必要か？
- .vimの管理はどうするか
- dockerの立ち上げ方はどうするか

など

**Comment by dondakeshimo** [comment]
Dockerfile.lsp
```
FROM ruby:2.7.1

COPY Gemfile* .

RUN bundle install && \
    gem install solargraph

WORKDIR /app

ENTRYPOINT ["solargraph"]
CMD ["socket", "--host", "0.0.0.0", "--port", "7658"]
```

docker-compose.yml
```
version: '3'

services:
  solargraph:
    container_name: solargraph
    image: estie-inc/medamayaki-solargraph:latest
    build:
      context: .
      dockerfile: Dockerfile.lsp
    volumes:
      - .:/app
    ports:
      - 7658:7658
```

.vim/coc-settings.json
```
{
    "solargraph.externalServer": {
        "host": "localhost",
        "port": 7658
    },
    "solargraph.transport": "external",
    "solargraph.diagnostics": true,
    "solargraph.hover": true,
    "solargraph.checkGemVersion": false
}
```

console
```
$ ls -l .ldfs
total 24
-rw-r--r--  1 dondakeshimo  staff   180 Nov 27 22:38 ^Users^dondakeshimo^src^github.com^hoge^Dockerfile.lsp.ldf
-rw-r--r--  1 dondakeshimo  staff  3079 Nov 27 22:38 ^Users^dondakeshimo^src^github.com^hoge^docker-compose.yml.ldf
```
